# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# Find a better way to do this - nonrecursively?

def calc_even_fib(n):
	even_fib = [2,8] 
	for i in range(2, n+1):
		even_fib.append(4*even_fib[i-1] + even_fib[i-2])
	return even_fib[n]

n = 0
answer = 0
while calc_even_fib(n) <= 4000000:
	answer += calc_even_fib(n)
	n += 1
	
print(answer) # 4613732